# FROM eclipse-temurin:21-jre

# WORKDIR /app

# COPY target/*.jar app.jar

# EXPOSE 8089

# ENTRYPOINT ["java", "-jar", "app.jar"]

FROM maven:3.9.9-eclipse-temurin-21 AS builder

WORKDIR /build
COPY . .
RUN mvn clean package -DskipTests

FROM eclipse-temurin:21-jre

WORKDIR /app
COPY --from=builder /build/target/*.jar app.jar

EXPOSE 8089

ENTRYPOINT ["java","-jar","app.jar"]
